SportsStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductRepository _repository;
        private readonly IOrderProcessor _orderProcessor;

        public CartController(IProductRepository repository, IOrderProcessor orderProcessor)
        {
            _repository = repository;
            _orderProcessor = orderProcessor;
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        // GET: Cart
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
                cart.AddItem(product, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
                cart.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout(Cart cart)
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                _orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

SportsStore.WebUI/Controllers/NavController.cs
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private readonly IProductRepository _repository;

        public NavController(IProductRepository repository)
        {
            _repository = repository;
        }

        public PartialViewResult Menu(string category = null, bool horizontalLayout = false)
        {
            NavViewModel model = new NavViewModel
            {
                Categories = _repository.Products.Select(p => p.Category).Distinct().OrderBy(p => p),
                SelectedCategory = category
            };
            return PartialView("Menu", model);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Web.Configuration;
using SportsStore.Domain.Abstract;
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _repository;
        public int PageSize = 4;

        public ProductController(IProductRepository repository)
        {
            _repository = repository;
        }

        public ViewResult List(int page = 1, string category = "")
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = _repository.Products
                    .Where(p => String.Equals(p.Category, category, StringComparison.CurrentCultureIgnoreCase) || string.IsNullOrEmpty(category))
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.Products.Count(p => String.Equals(p.Category, category, StringComparison.CurrentCultureIgnoreCase) || string.IsNullOrEmpty(category))
                },
                CurrentCategory = category,
                CategoryList = _repository.Products.Select(p => p.Category).Distinct().ToList()
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            return product != null ? File(product.ImageData, product.ImageMimeType) : null;
        }
    }
}

SportsStore.WebUI/Views/Shared/CategoryNavigation.cshtml
@model IEnumerable<string>

<ul>
    @foreach (string cat in Model)
    {
        <li>@Html.ActionLink(cat, "List", new { category = cat })</li>
    }
</ul>

SportsStore.WebUI/Views/Shared/ProductSummary.Mobile.cshtml
@model SportsStore.Domain.Entities.Product

<div data-role="collapsible" data-collapsed="false" data-contenttheme="c">
    <h2>
        @Model.Name
    </h2>
    <div class="ui-grid-b">
        <div class="ui-block-a">
            @Model.Description
        </div>
        <div class="ui-block-b">
            <strong>(@Model.Price.ToString("c"))</strong>
        </div>
        <div class="ui-block-c">
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                @Html.HiddenFor(x => x.ProductId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                <input type="submit" data-inline="true" data-mini="true" value="Add to cart" />
            }
        </div>
    </div>
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px;">
            <img class="img-thumbnail" height="75" width="75"
            src="@Url.Action("GetImage", "Product", new { Model.ProductId })"/>
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @if (Request.Url != null)
            {
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            }
            <input type="submit" class="btn btn-success" value="Add to Cart" />

        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@using System.Web.Optimization
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/Bootstrap")
    @Styles.Render("~/Content/ErrorStyles")
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    @Scripts.Render("~/Scripts/jQuery")
    @Scripts.Render("~/Scripts/jQueryValidation")
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1. 0">
    <link rel="stylesheet" href=" http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <h3>@Html.ActionLink("Sports Store", "List", "Product", new { page = 1 }, new { })</h3>
            @Html.Action("Menu", "Nav")
        </div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/Bootstrap")
    @Styles.Render("~/Content/Site")
    @Styles.Render("~/Content/ErrorStyles")
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="/">
            <span class="hidden-xs">SPORTS STORE</span>
            <div class="visible-xs">SPORTS</div>
            <div class="visible-xs">STORE</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="container-fluid">
        <div class="row panel">
            <div id="categories" class="visible-xs">
                @Html.Action("Menu", "Nav", new { horizontalLayout = true })
            </div>
            <div id="categories" class="col-xs-3 hidden-xs">
                @Html.Action("Menu", "Nav", new { horizontalLayout = false })
            </div>
            <div class="col-xs-12 col-sm-8">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/Scripts/jQuery")
    @Scripts.Render("~/Scripts/Bootstrap")
</body>
</html>