SportsStore.WebUI/Controllers/AdminController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly IProductRepository _productRepository;

        public AdminController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public ViewResult Index()
        {
            return View(_productRepository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);

            return View(product);
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        public ViewResult Delete(int productId)
        {
            Product product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);

            return View(product);
        }

        [HttpPost]
        public ActionResult Delete(Product product)
        {
            Product deletedProduct = _productRepository.Delete(product);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted", deletedProduct.Name);
            } return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase imageFile)
        {
            if (!ModelState.IsValid) return View(product);

            if (imageFile != null)
            {
                product.ImageMimeType = imageFile.ContentType;
                product.ImageData = new byte[imageFile.ContentLength];
                imageFile.InputStream.Read(product.ImageData, 0, imageFile.ContentLength);
            }

            _productRepository.Save(product);

            TempData["message"] = string.Format("{0} has been saved.", product.Name);

            return RedirectToAction("Index");
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Web.Configuration;
using SportsStore.Domain.Abstract;
using System.Linq;
using System.Web.Mvc;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _repository;
        public int PageSize = 4;

        public ProductController(IProductRepository repository)
        {
            _repository = repository;
        }

        public ViewResult List(int page = 1, string category = "")
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = _repository.Products
                    .Where(p => String.Equals(p.Category, category, StringComparison.CurrentCultureIgnoreCase) || string.IsNullOrEmpty(category))
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = _repository.Products.Count(p => String.Equals(p.Category, category, StringComparison.CurrentCultureIgnoreCase) || string.IsNullOrEmpty(category))
                },
                CurrentCategory = category,
                CategoryList = _repository.Products.Select(p => p.Category).Distinct().ToList()
            };

            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = _repository.Products.FirstOrDefault(p => p.ProductId == productId);

            return product != null ? File(product.ImageData, product.ImageMimeType) : null;
        }
    }
}

SportsStore.WebUI/Views/Admin/Delete.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Delete " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Delete @Model.Name</h3>
    </div>
    @using (Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductId)
            <h4>
                Are you sure you want to delete @Model.Name ?
            </h4>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Confirm Delete" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null,
                new
                {
                    @class = "btn btn-default"
                })
        </div>
    }
</div>

SportsStore.WebUI/Views/Admin/Edit.cshtml
@model SportsStore.Domain.Entities.Product

@{
    ViewBag.Title = "Admin: Edit " + @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.Name</h3>
    </div>
    @using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.ValidationSummary()
        <div class="panel-body">
            @Html.HiddenFor(m => m.ProductId)
            @foreach (ModelMetadata property in ViewData.ModelMetadata.Properties.Where(property => property.PropertyName != "ProductId"
                                                                                                    && property.PropertyName != "ImageData"
                                                                                                    && property.PropertyName != "ImageMimeType"))
            {
                <div class="form-group">
                    <label>
                        @(property.DisplayName ?? property.PropertyName)
                    </label>
                    @(property.PropertyName == "Description" ?
                          Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 }) :
                          Html.TextBox(property.PropertyName, null, new { @class = "form-control" }))
                    @Html.ValidationMessage(property.PropertyName)
                </div>
            }
            <div class="form-group">
                <div style="position: relative;">
                    <label>Image</label>
                    <a class="btn" href="javascript:;">
                        Choose file...
                        <input type="file" name="imageFile" size="40"
                               style="position: absolute;z-index: 2;top:0;left: 0;-ms-filter: 'alpha(opacity=0)'; opacity: 0;background-color: transparent;color: transparent;"
                               onchange="$('#upload-file-info').html($(this).val());" />
                    </a>
                    <span class="label label-info" id="upload-file-info"></span>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">No image</div>
                    }
                    else
                    {
                        <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductId })" alt="Product" />
                    }
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Cancel and return to List", "Index", null,
                new
                {
                    @class = "btn btn-default"
                })
        </div>
    }
</div>

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Domain.Entities.Product>

@{
    ViewBag.Title = "Admin: All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>All Products</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductId })</td>
                    <td class="text-right">@item.Price.ToString("c")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductId", item.ProductId)
                            @Html.ActionLink("Delete", "Delete", "Admin", new { productId = item.ProductId }, new { @class = "btn btn-default btn-xs" })
                            @*<input type="submit" class="btn btn-default btn-xs" value="Delete" />*@
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add a new Product", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>